/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Hunt.CurrentTestName = #TestFunc; \
  Hunt.CurrentTestLineNumber = TestLineNum; \
  Hunt.NumberOfTests++; \
  CMock_Init(); \
  HUNT_CLR_DETAILS(); \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
    CMock_Verify(); \
  } \
  CMock_Destroy(); \
  HuntConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "hunt.h"
#include "cmock.h"
#include <setjmp.h>
#include <stdio.h>
#include "funky.h"
#include <setjmp.h>
#include "Mockstanky.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_TheFirstThingToTest(void);
extern void test_TheSecondThingToTest(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  Mockstanky_Init();
}
static void CMock_Verify(void)
{
  Mockstanky_Verify();
}
static void CMock_Destroy(void)
{
  Mockstanky_Destroy();
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  CMock_Verify();
  CMock_Destroy();
  tearDown();
  CMock_Init();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  HuntBegin("testdata/mocksample.c");
  RUN_TEST(test_TheFirstThingToTest, 21);
  RUN_TEST(test_TheSecondThingToTest, 43);

  CMock_Guts_MemFreeFinal();
  return (HuntEnd());
}
